/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns 200 as long as the application can serve requests. No API key required.
         */
        get: operations["get_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Store a batch of UX events
         * @description Accepts 1 to 100 events of one frontend session. Events are stored as-is; aggregation happens later in SQL.
         */
        post: operations["post_api_telemetry_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Machine-readable error code in snake_case.
             * @example unauthorized
             * @enum {string}
             */
            error: "unauthorized" | "not_found" | "method_not_allowed" | "bad_request" | "internal_error";
        };
        Violation: {
            /**
             * @description Property path of the rejected value; array items are indexed.
             * @example events[0].type
             */
            field: string;
            /**
             * @description Human-readable message in German.
             * @example Unbekannter Event-Typ. Erlaubt sind: screen_view, time_on_screen, interaction, navigation.
             */
            message: string;
        };
        ValidationErrorResponse: {
            /**
             * @example validation_failed
             * @enum {string}
             */
            error: "validation_failed";
            violations: components["schemas"]["Violation"][];
        };
        TelemetryEventInput: {
            /**
             * @description Event type
             * @example interaction
             * @enum {string}
             */
            type: "screen_view" | "time_on_screen" | "interaction" | "navigation";
            /**
             * @description Screen or route the event happened on
             * @example session-new
             */
            screen: string;
            /**
             * Format: date-time
             * @description When the event happened on the client (ISO 8601)
             * @example 2026-09-07T09:58:12.345Z
             */
            occurredAt: string;
            /**
             * @description Interaction target (data-track value); null when not applicable
             * @default null
             * @example save-button
             */
            target: string | null;
            /**
             * @description Free-form event details; keys depend on the event type.
             * @default null
             * @example {
             *       "via": "click",
             *       "tag": "button"
             *     }
             */
            meta: {
                [key: string]: unknown;
            } | null;
        };
        TelemetryBatchRequest: {
            /**
             * @description Frontend that emitted the events
             * @example skate
             * @enum {string}
             */
            app: "skate" | "nutrition" | "habits";
            /**
             * Format: uuid
             * @description Random UUID generated per browser tab
             * @example 6f1c2d3e-4a5b-4c6d-8e9f-0a1b2c3d4e5f
             */
            sessionId: string;
            /** @description Between 1 and 100 events */
            events: components["schemas"]["TelemetryEventInput"][];
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /**
             * Format: date-time
             * @description Server time in UTC (ISO 8601)
             * @example 2026-09-07T10:00:00+00:00
             */
            time: string;
        };
        TelemetryAcceptedResponse: {
            /**
             * @description Number of events that were stored
             * @example 2
             */
            accepted: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "time": "2026-09-07T10:00:00+00:00"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_api_telemetry_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "app": "skate",
                 *       "sessionId": "6f1c2d3e-4a5b-4c6d-8e9f-0a1b2c3d4e5f",
                 *       "events": [
                 *         {
                 *           "type": "screen_view",
                 *           "screen": "home",
                 *           "occurredAt": "2026-09-07T09:58:12.345Z"
                 *         },
                 *         {
                 *           "type": "interaction",
                 *           "screen": "session-new",
                 *           "target": "save-button",
                 *           "meta": {
                 *             "trick": "kickflip"
                 *           },
                 *           "occurredAt": "2026-09-07T09:59:01.000Z"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["TelemetryBatchRequest"];
            };
        };
        responses: {
            /** @description Events stored */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "accepted": 2
                     *     }
                     */
                    "application/json": components["schemas"]["TelemetryAcceptedResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown route below /api */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong HTTP method for this route */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "method_not_allowed"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Payload rejected by validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "validation_failed",
                     *       "violations": [
                     *         {
                     *           "field": "events[0].type",
                     *           "message": "Unbekannter Event-Typ. Erlaubt sind: screen_view, time_on_screen, interaction, navigation."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
}
