/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns 200 as long as the application can serve requests. No API key required.
         */
        get: operations["get_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skate-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List skate sessions
         * @description Sessions newest first (sessionDate descending, then createdAt descending). Optionally filtered by date range.
         */
        get: operations["get_api_skate_sessions_list"];
        put?: never;
        /**
         * Create a skate session
         * @description Creates a session together with its practiced-trick rows.
         */
        post: operations["post_api_skate_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skate-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one skate session
         * @description Returns the session together with all of its practiced-trick rows.
         */
        get: operations["get_api_skate_sessions_get"];
        /**
         * Replace a skate session
         * @description Replaces the session fields and reconciles the trick rows: a slug that stays keeps its row id, a new slug becomes a new row, a slug no longer present is deleted.
         */
        put: operations["put_api_skate_sessions_update"];
        post?: never;
        /**
         * Delete a skate session
         * @description Deletes the session and all of its practiced-trick rows (ON DELETE CASCADE).
         */
        delete: operations["delete_api_skate_sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Store a batch of UX events
         * @description Accepts 1 to 100 events of one frontend session. Events are stored as-is; aggregation happens later in SQL.
         */
        post: operations["post_api_telemetry_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tricks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the trick catalog
         * @description Returns all 16 tricks with their direct prerequisites, sorted by difficulty ascending and, on a tie, by name ascending.
         */
        get: operations["get_api_tricks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tricks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one trick in detail
         * @description Description, derived progress, direct prerequisites and unlocked tricks with their own status, and the full session history (newest first, up to 100 entries). Refreshes trick_progress from session_trick before responding, same as GET /api/trick-tree.
         */
        get: operations["get_api_trick_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trick-recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next trick(s) to focus on
         * @description Up to focusLimit suggestions ranked by status, goalOrder, difficulty and slug, each with a German reasonCode and a recommended attempts/minutes dosage, plus an optional recovery hint for today.
         */
        get: operations["get_api_trick_recommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trick-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the full trick tree
         * @description Every trick with its derived status, session-derived numbers and prerequisite edges, plus the mastery policy thresholds. Refreshes trick_progress from session_trick before responding.
         */
        get: operations["get_api_trick_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Machine-readable error code in snake_case.
             * @example unauthorized
             * @enum {string}
             */
            error: "unauthorized" | "not_found" | "method_not_allowed" | "bad_request" | "internal_error";
        };
        Violation: {
            /**
             * @description Property path of the rejected value; array items are indexed.
             * @example events[0].type
             */
            field: string;
            /**
             * @description Human-readable message in German.
             * @example Unbekannter Event-Typ. Erlaubt sind: screen_view, time_on_screen, interaction, navigation.
             */
            message: string;
        };
        ValidationErrorResponse: {
            /**
             * @example validation_failed
             * @enum {string}
             */
            error: "validation_failed";
            violations: components["schemas"]["Violation"][];
        };
        SessionTrickInput: {
            /**
             * @description Slug of a catalog trick (T-0101)
             * @example ollie
             */
            trickSlug: string;
            /**
             * @description Number of attempts, 1 to 999
             * @example 30
             */
            attempts: number;
            /**
             * @description Number of landed attempts, 0 to attempts
             * @example 21
             */
            landed: number;
            /**
             * @description Optional note for this trick row
             * @default null
             * @example Zu frueh aufgesetzt.
             */
            notes: string | null;
        };
        SkateSessionRequest: {
            /**
             * Format: date
             * @description Session date, day precision
             * @example 2026-09-06
             */
            sessionDate: string;
            /**
             * Format: date-time
             * @description When the session started (ISO 8601 with offset)
             * @example 2026-09-06T16:30:00+02:00
             */
            startedAt?: string | null;
            /**
             * @description Duration in minutes, 1 to 600
             * @example 95
             */
            durationMinutes: number;
            /**
             * @description Where the session took place
             * @example Skatepark Braunschweig
             */
            location: string;
            /**
             * Format: float
             * @description Body weight before the session, in kg
             * @default null
             * @example 78.4
             */
            weightBeforeKg: number | null;
            /**
             * Format: float
             * @description Body weight after the session, in kg; only allowed together with weightBeforeKg
             * @default null
             * @example 77.1
             */
            weightAfterKg: number | null;
            /**
             * @description Perceived exertion, 1 to 10
             * @default null
             * @example 7
             */
            perceivedExertion: number | null;
            /**
             * @description Knee pain, 0 to 10
             * @default null
             * @example 3
             */
            kneePain: number | null;
            /**
             * @description Free-form notes
             * @default null
             * @example Manuals liefen gut, Knie ab 60 Minuten spuerbar.
             */
            notes: string | null;
            /**
             * @description Practiced tricks, at most 50 rows; trickSlug must be unique within the list
             * @default []
             */
            tricks: components["schemas"]["SessionTrickInput"][];
        };
        SkateSessionListQuery: {
            /**
             * Format: date
             * @description Only sessions with sessionDate >= from
             * @default null
             * @example 2026-09-01
             */
            from: string | null;
            /**
             * Format: date
             * @description Only sessions with sessionDate <= to
             * @default null
             * @example 2026-09-03
             */
            to: string | null;
            /**
             * @description Maximum number of items, 1 to 200
             * @default 50
             * @example 50
             */
            limit: number;
        };
        TelemetryEventInput: {
            /**
             * @description Event type
             * @example interaction
             * @enum {string}
             */
            type: "screen_view" | "time_on_screen" | "interaction" | "navigation";
            /**
             * @description Screen or route the event happened on
             * @example session-new
             */
            screen: string;
            /**
             * Format: date-time
             * @description When the event happened on the client (ISO 8601)
             * @example 2026-09-07T09:58:12.345Z
             */
            occurredAt: string;
            /**
             * @description Interaction target (data-track value); null when not applicable
             * @default null
             * @example save-button
             */
            target: string | null;
            /**
             * @description Free-form event details; keys depend on the event type.
             * @default null
             * @example {
             *       "via": "click",
             *       "tag": "button"
             *     }
             */
            meta: {
                [key: string]: unknown;
            } | null;
        };
        TelemetryBatchRequest: {
            /**
             * @description Frontend that emitted the events
             * @example skate
             * @enum {string}
             */
            app: "skate" | "nutrition" | "habits";
            /**
             * Format: uuid
             * @description Random UUID generated per browser tab
             * @example 6f1c2d3e-4a5b-4c6d-8e9f-0a1b2c3d4e5f
             */
            sessionId: string;
            /** @description Between 1 and 100 events */
            events: components["schemas"]["TelemetryEventInput"][];
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /**
             * Format: date-time
             * @description Server time in UTC (ISO 8601)
             * @example 2026-09-07T10:00:00+00:00
             */
            time: string;
        };
        SkateSessionSummary: {
            /**
             * @description Session ID
             * @example 01997d11-4c02-7a3e-8b55-2d9f10e4a7c1
             */
            id: string;
            /**
             * Format: date
             * @description Session date, day precision
             * @example 2026-09-06
             */
            sessionDate: string;
            /**
             * @description Duration in minutes
             * @example 95
             */
            durationMinutes: number;
            /**
             * @description Where the session took place
             * @example Skatepark Braunschweig
             */
            location: string;
            /**
             * @description Number of practiced-trick rows
             * @example 2
             */
            trickCount: number;
            /**
             * @description Derived: sum of all tricks[].attempts, 0 without tricks
             * @example 54
             */
            totalAttempts: number;
            /**
             * @description Derived: sum of all tricks[].landed
             * @example 30
             */
            totalLanded: number;
            /**
             * Format: float
             * @description Derived: totalLanded / totalAttempts, rounded to three decimals; null when totalAttempts is 0
             * @example 0.556
             */
            successRate?: number | null;
            /**
             * Format: float
             * @description Derived: weightBeforeKg - weightAfterKg, rounded to two decimals; null if either weight is missing
             * @example 1.3
             */
            fluidLossKg?: number | null;
            /**
             * @description Perceived exertion, 1 to 10
             * @example 7
             */
            perceivedExertion?: number | null;
            /**
             * @description Knee pain, 0 to 10
             * @example 3
             */
            kneePain?: number | null;
        };
        SkateSessionListResponse: {
            /** @description At most `limit` sessions, newest first */
            items: components["schemas"]["SkateSessionSummary"][];
            /**
             * @description Total number of matches before limit was applied
             * @example 5
             */
            total: number;
        };
        SessionTrickResponse: {
            /**
             * @description Trick row ID
             * @example 01997d11-4c02-7a3e-8b55-2d9f10e4a7c2
             */
            id: string;
            /**
             * @description Slug of the practiced catalog trick
             * @example ollie
             */
            trickSlug: string;
            /**
             * @description Catalog display name, spares a second lookup
             * @example Ollie
             */
            trickName: string;
            /**
             * @description Number of attempts
             * @example 30
             */
            attempts: number;
            /**
             * @description Number of landed attempts
             * @example 21
             */
            landed: number;
            /**
             * Format: float
             * @description landed / attempts, rounded to three decimals; never null since attempts >= 1
             * @example 0.7
             */
            successRate: number;
            /**
             * @description Optional note for this trick row
             * @example null
             */
            notes?: string | null;
        };
        SkateSessionResponse: {
            /**
             * @description Session ID
             * @example 01997d11-4c02-7a3e-8b55-2d9f10e4a7c1
             */
            id: string;
            /**
             * Format: date
             * @description Session date, day precision
             * @example 2026-09-06
             */
            sessionDate: string;
            /**
             * Format: date-time
             * @description When the session started (ISO 8601 with offset)
             * @example 2026-09-06T14:30:00+00:00
             */
            startedAt?: string | null;
            /**
             * @description Duration in minutes
             * @example 95
             */
            durationMinutes: number;
            /**
             * @description Where the session took place
             * @example Skatepark Braunschweig
             */
            location: string;
            /**
             * Format: float
             * @description Body weight before the session, in kg
             * @example 78.4
             */
            weightBeforeKg?: number | null;
            /**
             * Format: float
             * @description Body weight after the session, in kg
             * @example 77.1
             */
            weightAfterKg?: number | null;
            /**
             * Format: float
             * @description Derived: weightBeforeKg - weightAfterKg, rounded to two decimals; null if either weight is missing; may be negative
             * @example 1.3
             */
            fluidLossKg?: number | null;
            /**
             * @description Perceived exertion, 1 to 10
             * @example 7
             */
            perceivedExertion?: number | null;
            /**
             * @description Knee pain, 0 to 10
             * @example 3
             */
            kneePain?: number | null;
            /**
             * @description Free-form notes
             * @example Manuals liefen gut, Knie ab 60 Minuten spuerbar.
             */
            notes?: string | null;
            /**
             * Format: date-time
             * @description When this session was created
             * @example 2026-09-06T18:12:04+00:00
             */
            createdAt: string;
            /** @description Practiced tricks, in the order they were added */
            tricks: components["schemas"]["SessionTrickResponse"][];
            /**
             * @description Derived: sum of all tricks[].attempts, 0 without tricks
             * @example 54
             */
            totalAttempts: number;
            /**
             * @description Derived: sum of all tricks[].landed
             * @example 30
             */
            totalLanded: number;
            /**
             * Format: float
             * @description Derived: totalLanded / totalAttempts, rounded to three decimals; null when totalAttempts is 0
             * @example 0.556
             */
            successRate?: number | null;
        };
        TelemetryAcceptedResponse: {
            /**
             * @description Number of events that were stored
             * @example 2
             */
            accepted: number;
        };
        TrickResponse: {
            /**
             * @description Trick ID
             * @example 01997c6a-3b21-7c4e-9a10-4f2b6d8e1c35
             */
            id: string;
            /**
             * @description Unique, stable slug
             * @example ollie
             */
            slug: string;
            /**
             * @description Display name (German)
             * @example Ollie
             */
            name: string;
            /**
             * @description Movement category
             * @example flat
             */
            category: string;
            /**
             * @description Position in the tree, 1 to 10
             * @example 3
             */
            difficulty: number;
            /**
             * @description Optional description
             * @example Ollie in der Fahrt. Ausgangsniveau etwa 25 cm, Zielhöhe darüber.
             */
            description?: string | null;
            /**
             * @description Whether this trick is one of the seven contest goals
             * @example true
             */
            isGoal: boolean;
            /**
             * @description Position among the seven goals, 1 to 7
             * @example 1
             */
            goalOrder?: number | null;
            /**
             * @description Slugs of the direct prerequisites, alphabetically sorted
             * @example [
             *       "ollie-stand"
             *     ]
             */
            prerequisiteSlugs: string[];
        };
        TrickListResponse: {
            /** @description The full trick catalog */
            items: components["schemas"]["TrickResponse"][];
        };
        TrickDetailProgress: {
            /**
             * @description Derived progress status
             * @example uebe
             */
            status: string;
            /**
             * @description Total attempts across all sessions
             * @example 96
             */
            attemptsTotal: number;
            /**
             * @description Total landed attempts across all sessions
             * @example 21
             */
            landedTotal: number;
            /**
             * Format: float
             * @description landedTotal / attemptsTotal, three decimals; null when attemptsTotal is 0
             * @example 0.219
             */
            successRate?: number | null;
            /**
             * Format: float
             * @description Pooled success rate over the most recent qualifying sessions; null when none qualify
             * @example 0.267
             */
            recentSuccessRate?: number | null;
            /**
             * @description Number of sessions this trick was practiced in
             * @example 5
             */
            sessionCount: number;
            /**
             * Format: date
             * @description Date of the first session with at least one landed attempt
             * @example 2026-08-11
             */
            firstLandedOn?: string | null;
            /**
             * Format: date
             * @description Date of the most recent practiced session
             * @example 2026-09-06
             */
            lastPracticedOn?: string | null;
            /**
             * @description Server time this trick_progress row was last written, ISO 8601
             * @example 2026-09-06T18:12:44+00:00
             */
            updatedAt: string;
        };
        TrickRefView: {
            /**
             * @description Public trick key, not the UUID
             * @example ollie
             */
            slug: string;
            /**
             * @description Display name (German)
             * @example Ollie
             */
            name: string;
            /**
             * @description Derived progress status
             * @example sitzt
             */
            status: string;
        };
        TrickHistoryEntry: {
            /**
             * @description ID of the skate session this entry belongs to
             * @example 0192f3a1-7c4e-7b21-9f0a-6d2c1b8e4a55
             */
            sessionId: string;
            /**
             * Format: date
             * @description Date of the session
             * @example 2026-09-06
             */
            sessionDate: string;
            /**
             * @description Attempts in this session
             * @example 24
             */
            attempts: number;
            /**
             * @description Landed attempts in this session
             * @example 7
             */
            landed: number;
            /**
             * Format: float
             * @description landed / attempts, three decimals; null when attempts is 0
             * @example 0.292
             */
            successRate?: number | null;
            /**
             * @description Optional free-text note for this trick within this session
             * @example Rotation zu flach
             */
            notes?: string | null;
        };
        TrickPolicyView: {
            /**
             * Format: float
             * @description Success rate from which a trick counts as mastered
             * @example 0.75
             */
            masteryRate: number;
            /**
             * @description Number of most-recent qualifying sessions considered
             * @example 3
             */
            masterySessions: number;
            /**
             * @description Minimum attempts a session needs before it qualifies
             * @example 15
             */
            masteryMinAttempts: number;
            /**
             * @description each_session or pooled
             * @example each_session
             */
            masteryMode: string;
        };
        TrickDetailResponse: {
            /**
             * @description Public trick key, not the UUID
             * @example pop-shove-it
             */
            slug: string;
            /**
             * @description Display name (German)
             * @example Pop Shove-it
             */
            name: string;
            /**
             * @description Movement category
             * @example rotation
             */
            category: string;
            /**
             * @description Position in the tree, 1 to 10
             * @example 3
             */
            difficulty: number;
            /**
             * @description Whether this trick is one of the seven contest goals
             * @example true
             */
            isGoal: boolean;
            /**
             * @description Position among the seven goals, 1 to 7
             * @example 2
             */
            goalOrder?: number | null;
            /**
             * @description Optional description
             * @example Board dreht 180 Grad unter dir, Fuesse bleiben ueber dem Board.
             */
            description?: string | null;
            progress: components["schemas"]["TrickDetailProgress"];
            /** @description Direct prerequisites with their own status, sorted by difficulty then slug */
            requires: components["schemas"]["TrickRefView"][];
            /** @description Tricks this one directly unlocks, with their own status, sorted by difficulty then slug */
            unlocks: components["schemas"]["TrickRefView"][];
            /** @description Full session history, newest first, up to 100 entries */
            history: components["schemas"]["TrickHistoryEntry"][];
            policy: components["schemas"]["TrickPolicyView"];
        };
        TrickDosage: {
            /**
             * @description Minimum recommended attempts this session
             * @example 15
             */
            attemptsMin: number;
            /**
             * @description Maximum recommended attempts this session
             * @example 30
             */
            attemptsMax: number;
            /**
             * @description Minimum recommended minutes this session
             * @example 10
             */
            minutesMin: number;
            /**
             * @description Maximum recommended minutes this session
             * @example 20
             */
            minutesMax: number;
        };
        TrickSuggestion: {
            /**
             * @description Public trick key, not the UUID
             * @example pop-shove-it
             */
            slug: string;
            /**
             * @description Display name (German)
             * @example Pop Shove-it
             */
            name: string;
            /**
             * @description Derived progress status
             * @example uebe
             */
            status: string;
            /**
             * @description Machine-readable reason code
             * @example almost_landed
             */
            reasonCode: string;
            /**
             * @description German explanation for this suggestion
             * @example Du landest diesen Trick schon öfter, aber die Erfolgsquote ist noch nicht über mehrere Einheiten stabil – bleib dran.
             */
            reason: string;
            dosage: components["schemas"]["TrickDosage"];
        };
        PauseHintView: {
            /**
             * @description Machine-readable pause reason
             * @example knee_pain
             */
            code: string;
            /**
             * @description German explanation for the pause hint
             * @example Dein Knie meldet sich stärker als sonst – heute lieber kürzer treten oder pausieren, bei anhaltenden Schmerzen ärztlich abklären lassen.
             */
            message: string;
        };
        TrickRecommendationResponse: {
            /** @description The single best next trick to focus on; null when no trick is currently practicing or ready */
            primary?: components["schemas"]["TrickSuggestion"] | null;
            /** @description Further suggestions - primary plus secondary never exceed focusLimit */
            secondary: components["schemas"]["TrickSuggestion"][];
            /**
             * @description Maximum total number of suggestions (primary + secondary)
             * @example 2
             */
            focusLimit: number;
            /** @description Recovery hint for today; null when neither threshold is met */
            pauseHint?: components["schemas"]["PauseHintView"] | null;
            /**
             * @description Server time of this response, ISO 8601
             * @example 2026-09-08T17:41:02+00:00
             */
            generatedAt: string;
        };
        TrickTreeNode: {
            /**
             * @description Public trick key, not the UUID
             * @example ollie
             */
            slug: string;
            /**
             * @description Display name (German)
             * @example Ollie
             */
            name: string;
            /**
             * @description Movement category
             * @example flat
             */
            category: string;
            /**
             * @description Position in the tree, 1 to 10
             * @example 2
             */
            difficulty: number;
            /**
             * @description Whether this trick is one of the seven contest goals
             * @example true
             */
            isGoal: boolean;
            /**
             * @description Position among the seven goals, 1 to 7
             * @example 1
             */
            goalOrder?: number | null;
            /**
             * @description Derived progress status
             * @example sitzt
             */
            status: string;
            /**
             * @description Total attempts across all sessions
             * @example 412
             */
            attemptsTotal: number;
            /**
             * @description Total landed attempts across all sessions
             * @example 318
             */
            landedTotal: number;
            /**
             * Format: float
             * @description landedTotal / attemptsTotal, three decimals, via App\Service\Skate\SessionMetrics::successRate(); null when attemptsTotal is 0
             * @example 0.772
             */
            successRate?: number | null;
            /**
             * Format: float
             * @description Pooled success rate over the most recent qualifying sessions; null when none qualify
             * @example 0.81
             */
            recentSuccessRate?: number | null;
            /**
             * @description Number of sessions this trick was practiced in
             * @example 14
             */
            sessionCount: number;
            /**
             * Format: date
             * @description Date of the first session with at least one landed attempt
             * @example 2026-04-19
             */
            firstLandedOn?: string | null;
            /**
             * Format: date
             * @description Date of the most recent practiced session
             * @example 2026-09-06
             */
            lastPracticedOn?: string | null;
        };
        TrickTreeEdge: {
            /**
             * @description Slug of the prerequisite trick
             * @example ollie-stand
             */
            from: string;
            /**
             * @description Slug of the dependent trick
             * @example ollie
             */
            to: string;
        };
        TrickTreeResponse: {
            /** @description All tricks, sorted by goalOrder ascending (null last), then difficulty, then slug */
            nodes: components["schemas"]["TrickTreeNode"][];
            /** @description One edge per prerequisite, from the prerequisite to the dependent trick, sorted by from then to */
            edges: components["schemas"]["TrickTreeEdge"][];
            policy: components["schemas"]["TrickPolicyView"];
            /**
             * @description Server time of this response, ISO 8601
             * @example 2026-09-08T17:41:02+00:00
             */
            generatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "time": "2026-09-07T10:00:00+00:00"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_api_skate_sessions_list: {
        parameters: {
            query?: {
                /**
                 * @description Only sessions with sessionDate >= from
                 * @example 2026-09-01
                 */
                from?: string | null;
                /**
                 * @description Only sessions with sessionDate <= to
                 * @example 2026-09-03
                 */
                to?: string | null;
                /**
                 * @description Maximum number of items, 1 to 200
                 * @example 50
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "01997d11-4c02-7a3e-8b55-2d9f10e4a7c1",
                     *           "sessionDate": "2026-09-06",
                     *           "durationMinutes": 95,
                     *           "location": "Skatepark Braunschweig",
                     *           "trickCount": 2,
                     *           "totalAttempts": 54,
                     *           "totalLanded": 30,
                     *           "successRate": 0.556,
                     *           "fluidLossKg": 1.3,
                     *           "perceivedExertion": 7,
                     *           "kneePain": 3
                     *         }
                     *       ],
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["SkateSessionListResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description limit outside 1-200, or from after to */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "validation_failed",
                     *       "violations": [
                     *         {
                     *           "field": "from",
                     *           "message": "Das Start-Datum darf nicht nach dem End-Datum liegen."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    post_api_skate_sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "sessionDate": "2026-09-06",
                 *       "startedAt": "2026-09-06T16:30:00+02:00",
                 *       "durationMinutes": 95,
                 *       "location": "Skatepark Braunschweig",
                 *       "weightBeforeKg": 78.4,
                 *       "weightAfterKg": 77.1,
                 *       "perceivedExertion": 7,
                 *       "kneePain": 3,
                 *       "notes": "Manuals liefen gut, Knie ab 60 Minuten spuerbar.",
                 *       "tricks": [
                 *         {
                 *           "trickSlug": "ollie",
                 *           "attempts": 30,
                 *           "landed": 21,
                 *           "notes": null
                 *         },
                 *         {
                 *           "trickSlug": "manual",
                 *           "attempts": 24,
                 *           "landed": 9,
                 *           "notes": "Zu frueh aufgesetzt."
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["SkateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    /** @description URL of the new session */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkateSessionResponse"];
                };
            };
            /** @description Malformed JSON body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "bad_request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Payload rejected by validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "validation_failed",
                     *       "violations": [
                     *         {
                     *           "field": "sessionDate",
                     *           "message": "Das Datum darf nicht in der Zukunft liegen."
                     *         },
                     *         {
                     *           "field": "tricks[0].landed",
                     *           "message": "Es koennen nicht mehr Treffer als Versuche sein."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_api_skate_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkateSessionResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown or formally invalid ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_api_skate_sessions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkateSessionRequest"];
            };
        };
        responses: {
            /** @description Session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkateSessionResponse"];
                };
            };
            /** @description Malformed JSON body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "bad_request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Payload rejected by validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    delete_api_skate_sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_telemetry_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "app": "skate",
                 *       "sessionId": "6f1c2d3e-4a5b-4c6d-8e9f-0a1b2c3d4e5f",
                 *       "events": [
                 *         {
                 *           "type": "screen_view",
                 *           "screen": "home",
                 *           "occurredAt": "2026-09-07T09:58:12.345Z"
                 *         },
                 *         {
                 *           "type": "interaction",
                 *           "screen": "session-new",
                 *           "target": "save-button",
                 *           "meta": {
                 *             "trick": "kickflip"
                 *           },
                 *           "occurredAt": "2026-09-07T09:59:01.000Z"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["TelemetryBatchRequest"];
            };
        };
        responses: {
            /** @description Events stored */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "accepted": 2
                     *     }
                     */
                    "application/json": components["schemas"]["TelemetryAcceptedResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown route below /api */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong HTTP method for this route */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "method_not_allowed"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Payload rejected by validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "validation_failed",
                     *       "violations": [
                     *         {
                     *           "field": "events[0].type",
                     *           "message": "Unbekannter Event-Typ. Erlaubt sind: screen_view, time_on_screen, interaction, navigation."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    get_api_tricks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full trick catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "01997c6a-3b21-7c4e-9a10-4f2b6d8e1c30",
                     *           "slug": "rolling",
                     *           "name": "Sicher rollen",
                     *           "category": "flat",
                     *           "difficulty": 1,
                     *           "description": "Pushen, Richtung halten, bremsen und in der Fahrt stehen.",
                     *           "isGoal": false,
                     *           "goalOrder": null,
                     *           "prerequisiteSlugs": []
                     *         },
                     *         {
                     *           "id": "01997c6a-3b21-7c4e-9a10-4f2b6d8e1c35",
                     *           "slug": "ollie",
                     *           "name": "Ollie",
                     *           "category": "flat",
                     *           "difficulty": 3,
                     *           "description": "Ollie in der Fahrt. Ausgangsniveau etwa 25 cm, Zielhöhe darüber.",
                     *           "isGoal": true,
                     *           "goalOrder": 1,
                     *           "prerequisiteSlugs": [
                     *             "ollie-stand"
                     *           ]
                     *         },
                     *         {
                     *           "id": "01997c6a-3b21-7c4e-9a10-4f2b6d8e1c39",
                     *           "slug": "ollie-to-manual",
                     *           "name": "Ollie in den Manual",
                     *           "category": "balance",
                     *           "difficulty": 6,
                     *           "description": "Ollie auf das Manual-Pad und direkt in den Manual abrollen.",
                     *           "isGoal": true,
                     *           "goalOrder": 4,
                     *           "prerequisiteSlugs": [
                     *             "manual",
                     *             "ollie"
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["TrickListResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong HTTP method for this route */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "method_not_allowed"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_trick_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trick detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "slug": "pop-shove-it",
                     *       "name": "Pop Shove-it",
                     *       "category": "rotation",
                     *       "difficulty": 3,
                     *       "isGoal": true,
                     *       "goalOrder": 2,
                     *       "description": "Board dreht 180 Grad unter dir, Fuesse bleiben ueber dem Board.",
                     *       "progress": {
                     *         "status": "uebe",
                     *         "attemptsTotal": 96,
                     *         "landedTotal": 21,
                     *         "successRate": 0.219,
                     *         "recentSuccessRate": 0.267,
                     *         "sessionCount": 5,
                     *         "firstLandedOn": "2026-08-11",
                     *         "lastPracticedOn": "2026-09-06",
                     *         "updatedAt": "2026-09-06T18:12:44+00:00"
                     *       },
                     *       "requires": [
                     *         {
                     *           "slug": "ollie",
                     *           "name": "Ollie",
                     *           "status": "sitzt"
                     *         }
                     *       ],
                     *       "unlocks": [
                     *         {
                     *           "slug": "pop-shove-it-to-manual",
                     *           "name": "Pop Shove-it in den Manual",
                     *           "status": "gesperrt"
                     *         }
                     *       ],
                     *       "history": [
                     *         {
                     *           "sessionId": "0192f3a1-7c4e-7b21-9f0a-6d2c1b8e4a55",
                     *           "sessionDate": "2026-09-06",
                     *           "attempts": 24,
                     *           "landed": 7,
                     *           "successRate": 0.292,
                     *           "notes": "Rotation zu flach"
                     *         },
                     *         {
                     *           "sessionId": "0192e88c-2b10-7a49-8f31-40c9b7e2d611",
                     *           "sessionDate": "2026-09-02",
                     *           "attempts": 20,
                     *           "landed": 4,
                     *           "successRate": 0.2,
                     *           "notes": null
                     *         }
                     *       ],
                     *       "policy": {
                     *         "masteryRate": 0.75,
                     *         "masterySessions": 3,
                     *         "masteryMinAttempts": 15,
                     *         "masteryMode": "each_session"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["TrickDetailResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown or formally invalid slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong HTTP method for this route */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "method_not_allowed"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_trick_recommendation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current recommendation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "primary": {
                     *         "slug": "pop-shove-it",
                     *         "name": "Pop Shove-it",
                     *         "status": "uebe",
                     *         "reasonCode": "almost_landed",
                     *         "reason": "Du landest diesen Trick schon öfter, aber die Erfolgsquote ist noch nicht über mehrere Einheiten stabil – bleib dran.",
                     *         "dosage": {
                     *           "attemptsMin": 15,
                     *           "attemptsMax": 30,
                     *           "minutesMin": 10,
                     *           "minutesMax": 20
                     *         }
                     *       },
                     *       "secondary": [
                     *         {
                     *           "slug": "manual",
                     *           "name": "Manual",
                     *           "status": "uebe",
                     *           "reasonCode": "consolidate",
                     *           "reason": "Diesen Trick beherrschst du schon – übe ihn ab und zu weiter, damit er sitzen bleibt.",
                     *           "dosage": {
                     *             "attemptsMin": 15,
                     *             "attemptsMax": 30,
                     *             "minutesMin": 10,
                     *             "minutesMax": 20
                     *           }
                     *         }
                     *       ],
                     *       "focusLimit": 2,
                     *       "pauseHint": {
                     *         "code": "knee_pain",
                     *         "message": "Dein Knie meldet sich stärker als sonst – heute lieber kürzer treten oder pausieren, bei anhaltenden Schmerzen ärztlich abklären lassen."
                     *       },
                     *       "generatedAt": "2026-09-08T17:41:02+00:00"
                     *     }
                     */
                    "application/json": components["schemas"]["TrickRecommendationResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong HTTP method for this route */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "method_not_allowed"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "internal_error"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_trick_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full trick tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "nodes": [
                     *         {
                     *           "slug": "ollie",
                     *           "name": "Ollie",
                     *           "category": "flat",
                     *           "difficulty": 2,
                     *           "isGoal": true,
                     *           "goalOrder": 1,
                     *           "status": "sitzt",
                     *           "attemptsTotal": 412,
                     *           "landedTotal": 318,
                     *           "successRate": 0.772,
                     *           "recentSuccessRate": 0.81,
                     *           "sessionCount": 14,
                     *           "firstLandedOn": "2026-04-19",
                     *           "lastPracticedOn": "2026-09-06"
                     *         },
                     *         {
                     *           "slug": "boardslide",
                     *           "name": "Boardslide",
                     *           "category": "slide",
                     *           "difficulty": 6,
                     *           "isGoal": true,
                     *           "goalOrder": 6,
                     *           "status": "gesperrt",
                     *           "attemptsTotal": 0,
                     *           "landedTotal": 0,
                     *           "successRate": null,
                     *           "recentSuccessRate": null,
                     *           "sessionCount": 0,
                     *           "firstLandedOn": null,
                     *           "lastPracticedOn": null
                     *         }
                     *       ],
                     *       "edges": [
                     *         {
                     *           "from": "ollie",
                     *           "to": "pop-shove-it"
                     *         },
                     *         {
                     *           "from": "ollie",
                     *           "to": "boardslide"
                     *         }
                     *       ],
                     *       "policy": {
                     *         "masteryRate": 0.75,
                     *         "masterySessions": 3,
                     *         "masteryMinAttempts": 15,
                     *         "masteryMode": "each_session"
                     *       },
                     *       "generatedAt": "2026-09-08T17:41:02+00:00"
                     *     }
                     */
                    "application/json": components["schemas"]["TrickTreeResponse"];
                };
            };
            /** @description Missing or invalid X-Api-Key header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong HTTP method for this route */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "method_not_allowed"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
