/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as TricksIndexRouteImport } from './routes/tricks/index'
import { Route as TricksSlugRouteImport } from './routes/tricks/$slug'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as SessionsSessionIdEditRouteImport } from './routes/sessions/$sessionId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksIndexRoute = TricksIndexRouteImport.update({
  id: '/tricks/',
  path: '/tricks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksSlugRoute = TricksSlugRouteImport.update({
  id: '/tricks/$slug',
  path: '/tricks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdEditRoute = SessionsSessionIdEditRouteImport.update({
  id: '/sessions/$sessionId/edit',
  path: '/sessions/$sessionId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/training': typeof TrainingRoute
  '/sessions/new': typeof SessionsNewRoute
  '/tricks/$slug': typeof TricksSlugRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tricks/': typeof TricksIndexRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/training': typeof TrainingRoute
  '/sessions/new': typeof SessionsNewRoute
  '/tricks/$slug': typeof TricksSlugRoute
  '/sessions': typeof SessionsIndexRoute
  '/tricks': typeof TricksIndexRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/training': typeof TrainingRoute
  '/sessions/new': typeof SessionsNewRoute
  '/tricks/$slug': typeof TricksSlugRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tricks/': typeof TricksIndexRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/training'
    | '/sessions/new'
    | '/tricks/$slug'
    | '/sessions/'
    | '/tricks/'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/training'
    | '/sessions/new'
    | '/tricks/$slug'
    | '/sessions'
    | '/tricks'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/training'
    | '/sessions/new'
    | '/tricks/$slug'
    | '/sessions/'
    | '/tricks/'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrainingRoute: typeof TrainingRoute
  SessionsNewRoute: typeof SessionsNewRoute
  TricksSlugRoute: typeof TricksSlugRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TricksIndexRoute: typeof TricksIndexRoute
  SessionsSessionIdEditRoute: typeof SessionsSessionIdEditRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks/': {
      id: '/tricks/'
      path: '/tricks'
      fullPath: '/tricks/'
      preLoaderRoute: typeof TricksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks/$slug': {
      id: '/tricks/$slug'
      path: '/tricks/$slug'
      fullPath: '/tricks/$slug'
      preLoaderRoute: typeof TricksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/edit': {
      id: '/sessions/$sessionId/edit'
      path: '/sessions/$sessionId/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof SessionsSessionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrainingRoute: TrainingRoute,
  SessionsNewRoute: SessionsNewRoute,
  TricksSlugRoute: TricksSlugRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TricksIndexRoute: TricksIndexRoute,
  SessionsSessionIdEditRoute: SessionsSessionIdEditRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
